{% set name = "tracerite" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tracerite-{{ version }}.tar.gz
  sha256: 327ecff4aeb479f6bf97c23ded2dd2581f70505dc3f932d431afde03dba749d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - html5tagger >=1.2.1

test:
  imports:
    - tracerite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sanic-org/tracerite
  summary: Human-readable HTML tracebacks for Python exceptions
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
