{% set name = "tracerite" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tracerite-{{ version }}.tar.gz
  sha256: 6400a35a187747189e4bb8d4a8e471bd86d14dbdcc94bcad23f4eda023f41356

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - setuptools-scm
    - pip
  run:
    - python >=3.0
    - html5tagger >=1.2.1

test:
  imports:
    - tracerite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanic-org/tracerite
  summary: Human-readable HTML tracebacks for Python exceptions
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
