{% set name = "tracerite" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tracerite-{{ version }}.tar.gz
  sha256: 041dab8fd4bb405f73506293ac7438a2d311e5f9044378ba7d9a6540392f9e4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - setuptools-scm
    - pip
  run:
    - python >=3.0
    - html5tagger >=1.2.1

test:
  imports:
    - tracerite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanic-org/tracerite
  summary: Human-readable HTML tracebacks for Python exceptions
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
