schema_version: 1

context:
  name: tracerite
  version: "2.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tracerite-${{ version }}.tar.gz
  sha256: 6fd915137f4d041fa27f1ca89107d392287927e3b857d9448ef46dbf2ef116ad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - html5tagger >=2.0.0

tests:
  - python:
      imports:
        - tracerite
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Human-readable HTML tracebacks for Python exceptions
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/sanic-org/tracerite

extra:
  recipe-maintainers:
    - thewchan
