schema_version: 1

context:
  name: tracerite
  version: "2.6.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tracerite-${{ version }}.tar.gz
  sha256: c661f9067f1e5d3fd30f995174e6db61be15bed621b827e1e31f2d402a45fcbc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - html5tagger >=2.0.0

tests:
  - python:
      imports:
        - tracerite
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Human-readable HTML tracebacks for Python exceptions
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/sanic-org/tracerite

extra:
  recipe-maintainers:
    - thewchan
